# <span style='color:blue'> <u>NumPy</u> <i>('NUM-erical PY-thon')</i> </span>

In [12]:
import numpy as np
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2 = np.random.randint(10,size=(3,4))     #Creates a 3x4 array of rand integers between [0,10)
print(mat1,'\n\n',mat2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[8 3 2 2]
 [1 4 1 8]
 [9 9 6 1]]


In [24]:
print(" Mat2 dim: "'\t',mat2.ndim,'\n',"Mat2 shape: "'\t',mat2.shape,'\n', "Mat2 size: "'\t',mat2.size)
print(" Mat2 DataType: ",mat2.dtype)

 Mat2 dim: 	 2 
 Mat2 shape: 	 (3, 4) 
 Mat2 size: 	 12
 Mat2 DataType:  int32


## <span style='color:blue'> Array Indexing, Slicing, Reshaping & Concatenation </span>

In [28]:
mat1[0,1]   #Element at 1st row,2nd column

2

In [29]:
mat1[0,-1]   #Element at 1st row,last column

3

In [33]:
mat1[:2,:2]   #All elements till first 2 rows and 2 cloumns

array([[1, 2],
       [4, 5]])

In [38]:
mat1[:2,::2]   #First 2 rows and every second column

array([[1, 3],
       [4, 6]])

In [40]:
mat2.reshape((2,6))

array([[8, 3, 2, 2, 1, 4],
       [1, 8, 9, 9, 6, 1]])

In [44]:
# Horizontal Stacking
np.hstack([mat1,mat2])

array([[1, 2, 3, 8, 3, 2, 2],
       [4, 5, 6, 1, 4, 1, 8],
       [7, 8, 9, 9, 9, 6, 1]])

In [45]:
# Vertical Stacking
np.vstack([mat1,mat2.reshape(4,3)])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [8, 3, 2],
       [2, 1, 4],
       [1, 8, 9],
       [9, 6, 1]])

In [59]:
# Splitting an array
a =np.split(mat2,[2])
print("a1 : ",a[0])
print("a2 : ",a[1],"\n")

b = np.hsplit(mat2,[2])
print(b)

a1 :  [[8 3 2 2]
 [1 4 1 8]]
a2 :  [[9 9 6 1]] 

[array([[8, 3],
       [1, 4],
       [9, 9]]), array([[2, 2],
       [1, 8],
       [6, 1]])]


In [63]:
# Useful functions
print("Max Value: ",np.max(mat2))
print("Cosine ",np.cos(mat2))

Max Value:  9
Cosine  [[-0.14550003 -0.9899925  -0.41614684 -0.41614684]
 [ 0.54030231 -0.65364362  0.54030231 -0.14550003]
 [-0.91113026 -0.91113026  0.96017029  0.54030231]]


In [67]:
np.add.reduce(mat1) #Reduce to single row by adding all columns

array([12, 15, 18])

In [66]:
np.multiply.reduce(mat1)  #Reduce to single row by adding all columns

array([ 28,  80, 162])

In [68]:
np.sum(mat1) # Sum all elements

45

## <span style='color:blue'> Vector & Matrix Operations </span>

In [74]:
mat1 * mat1  # Element by Element Mul

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [75]:
mat1.T    # Transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [76]:
mat1@mat2  # (3x3) * (3x4) matrix mul

array([[ 37,  38,  22,  21],
       [ 91,  86,  49,  54],
       [145, 134,  76,  87]])

In [77]:
np.dot(mat1[:,0],mat1[:,1]) # dot product of 2 column vectors

78

In [78]:
np.linalg.inv(mat1)  # matrix inverse

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [80]:
np.linalg.matrix_rank(mat1)   # rank


2

In [83]:
s,V = np.linalg.eig(mat1)
print("Eigen Values: ",s)
print("Eigen Vectors: ",V)

Eigen Values:  [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Eigen Vectors:  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
